// ECO opening database — longest-match wins in identifyOpening()
// moves: space-separated SAN string exactly as chess.js outputs
const ECO = [
  // ── Flank / other first moves ──────────────────────────────────────────
  { eco: 'A00', name: "Bird's Opening",              moves: 'f4' },
  { eco: 'A00', name: 'Nimzowitsch-Larsen Attack',   moves: 'b3' },
  { eco: 'A00', name: "King's Fianchetto Opening",   moves: 'g3' },
  { eco: 'A00', name: 'Grob Attack',                 moves: 'g4' },
  { eco: 'A00', name: "Van't Kruijs Opening",        moves: 'e3' },
  { eco: 'A01', name: 'Nimzowitsch-Larsen Attack',   moves: 'b3 e5' },
  { eco: 'A02', name: "Bird's Opening, Dutch Var.",  moves: 'f4 f5' },
  { eco: 'A04', name: 'Réti Opening',                moves: 'Nf3' },
  { eco: 'A05', name: 'Réti Opening',                moves: 'Nf3 Nf6' },
  { eco: 'A06', name: 'Réti Opening',                moves: 'Nf3 d5' },
  { eco: 'A07', name: "Réti, King's Indian Attack",  moves: 'Nf3 d5 g3' },

  // ── English Opening ────────────────────────────────────────────────────
  { eco: 'A10', name: 'English Opening',                          moves: 'c4' },
  { eco: 'A10', name: 'English, Anglo-Scandinavian',              moves: 'c4 d5' },
  { eco: 'A11', name: 'English, Caro-Kann Defence',               moves: 'c4 c6' },
  { eco: 'A13', name: 'English, Agincourt Defence',               moves: 'c4 e6' },
  { eco: 'A15', name: 'English, Anglo-Indian Defence',            moves: 'c4 Nf6' },
  { eco: 'A20', name: "English, King's English",                  moves: 'c4 e5' },
  { eco: 'A25', name: "English, King's English, Four Knights",    moves: 'c4 e5 Nc3 Nc6' },
  { eco: 'A30', name: 'English, Symmetrical Variation',           moves: 'c4 c5' },

  // ── Queen's Pawn ───────────────────────────────────────────────────────
  { eco: 'A40', name: "Queen's Pawn Game",   moves: 'd4' },
  { eco: 'A40', name: "Queen's Pawn Game",   moves: 'd4 e6' },
  { eco: 'A40', name: "Queen's Pawn Game",   moves: 'd4 c5' },
  { eco: 'A41', name: "Queen's Pawn Game",   moves: 'd4 d6' },
  { eco: 'A45', name: 'Trompowsky Attack',   moves: 'd4 Nf6 Bg5' },
  { eco: 'A80', name: 'Dutch Defence',       moves: 'd4 f5' },
  { eco: 'A84', name: 'Dutch Defence',       moves: 'd4 f5 c4' },
  { eco: 'D00', name: "Queen's Pawn Game",   moves: 'd4 d5' },

  // ── Queen's Gambit ─────────────────────────────────────────────────────
  { eco: 'D06', name: "Queen's Gambit",                      moves: 'd4 d5 c4' },
  { eco: 'D20', name: "Queen's Gambit Accepted",             moves: 'd4 d5 c4 dxc4' },
  { eco: 'D21', name: "Queen's Gambit Accepted",             moves: 'd4 d5 c4 dxc4 Nf3' },
  { eco: 'D10', name: 'Slav Defence',                        moves: 'd4 d5 c4 c6' },
  { eco: 'D11', name: 'Slav Defence',                        moves: 'd4 d5 c4 c6 Nf3 Nf6' },
  { eco: 'D15', name: 'Slav Defence, Accepted',              moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4' },
  { eco: 'D30', name: "Queen's Gambit Declined",             moves: 'd4 d5 c4 e6' },
  { eco: 'D31', name: "Queen's Gambit Declined",             moves: 'd4 d5 c4 e6 Nc3' },
  { eco: 'D35', name: "Queen's Gambit Declined, Exchange",   moves: 'd4 d5 c4 e6 Nc3 Nf6 cxd5 exd5' },
  { eco: 'D37', name: "Queen's Gambit Declined",             moves: 'd4 d5 c4 e6 Nc3 Nf6 Nf3' },
  { eco: 'D43', name: 'Semi-Slav Defence',                   moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6' },
  { eco: 'D44', name: 'Semi-Slav, Anti-Meran Gambit',        moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5 dxc4' },
  { eco: 'D45', name: 'Semi-Slav Defence',                   moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3' },
  { eco: 'D50', name: "Queen's Gambit Declined, 4.Bg5",      moves: 'd4 d5 c4 e6 Nc3 Nf6 Bg5' },
  { eco: 'D55', name: "Queen's Gambit Declined",             moves: 'd4 d5 c4 e6 Nc3 Nf6 Bg5 Be7' },
  { eco: 'D60', name: "Queen's Gambit Declined, Orthodox",   moves: 'd4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O' },

  // ── Grünfeld ───────────────────────────────────────────────────────────
  { eco: 'D70', name: 'Grünfeld Defence',               moves: 'd4 Nf6 c4 g6 Nc3 d5' },
  { eco: 'D80', name: 'Grünfeld Defence',               moves: 'd4 Nf6 c4 g6 Nc3 d5 Bg5' },
  { eco: 'D85', name: 'Grünfeld, Exchange Variation',   moves: 'd4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3' },

  // ── King's Indian ──────────────────────────────────────────────────────
  { eco: 'E60', name: "King's Indian Defence",                 moves: 'd4 Nf6 c4 g6' },
  { eco: 'E61', name: "King's Indian Defence",                 moves: 'd4 Nf6 c4 g6 Nc3 Bg7' },
  { eco: 'E62', name: "King's Indian, Fianchetto Variation",   moves: 'd4 Nf6 c4 g6 Nc3 Bg7 Nf3 O-O g3' },
  { eco: 'E70', name: "King's Indian, Averbakh Variation",     moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Bg5' },
  { eco: 'E76', name: "King's Indian, Four Pawns Attack",      moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f4' },
  { eco: 'E80', name: "King's Indian, Sämisch Variation",      moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3' },
  { eco: 'E90', name: "King's Indian, Classical Variation",    moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3' },
  { eco: 'E97', name: "King's Indian, Classical, Mar del Plata",moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5' },

  // ── Nimzo-Indian ───────────────────────────────────────────────────────
  { eco: 'E20', name: 'Nimzo-Indian Defence',                     moves: 'd4 Nf6 c4 e6 Nc3 Bb4' },
  { eco: 'E21', name: 'Nimzo-Indian, Three Knights',              moves: 'd4 Nf6 c4 e6 Nc3 Bb4 Nf3' },
  { eco: 'E32', name: 'Nimzo-Indian, Classical Variation',        moves: 'd4 Nf6 c4 e6 Nc3 Bb4 Qc2' },
  { eco: 'E40', name: 'Nimzo-Indian, 4.e3',                       moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3' },
  { eco: 'E48', name: 'Nimzo-Indian, 4.e3 O-O',                   moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3 O-O' },
  { eco: 'E55', name: 'Nimzo-Indian, 4.e3, Gligoric System',      moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5' },

  // ── Queen's Indian ─────────────────────────────────────────────────────
  { eco: 'E10', name: "Queen's Indian Defence",              moves: 'd4 Nf6 c4 e6 Nf3' },
  { eco: 'E12', name: "Queen's Indian Defence",              moves: 'd4 Nf6 c4 e6 Nf3 b6' },
  { eco: 'E15', name: "Queen's Indian, Nimzowitsch Var.",    moves: 'd4 Nf6 c4 e6 Nf3 b6 Nc3' },
  { eco: 'E17', name: "Queen's Indian, Classical",           moves: 'd4 Nf6 c4 e6 Nf3 b6 g3 Bb7 Bg2 Be7' },

  // ── Catalan ────────────────────────────────────────────────────────────
  { eco: 'E00', name: 'Catalan Opening',            moves: 'd4 Nf6 c4 e6 g3' },
  { eco: 'E04', name: 'Catalan, Open Variation',    moves: 'd4 Nf6 c4 e6 g3 d5 Bg2 dxc4' },
  { eco: 'E06', name: 'Catalan, Closed Variation',  moves: 'd4 Nf6 c4 e6 g3 d5 Bg2 Be7' },

  // ── French Defence ─────────────────────────────────────────────────────
  { eco: 'C00', name: 'French Defence',                   moves: 'e4 e6' },
  { eco: 'C00', name: 'French Defence',                   moves: 'e4 e6 d4 d5' },
  { eco: 'C01', name: 'French, Exchange Variation',       moves: 'e4 e6 d4 d5 exd5 exd5' },
  { eco: 'C02', name: 'French, Advance Variation',        moves: 'e4 e6 d4 d5 e5' },
  { eco: 'C03', name: 'French, Tarrasch Variation',       moves: 'e4 e6 d4 d5 Nd2' },
  { eco: 'C06', name: 'French, Tarrasch, Closed',         moves: 'e4 e6 d4 d5 Nd2 Nf6 Bd3 c5 c3 Nc6 Ne2' },
  { eco: 'C10', name: 'French, Rubinstein Variation',     moves: 'e4 e6 d4 d5 Nc3 dxe4' },
  { eco: 'C11', name: 'French, Classical Variation',      moves: 'e4 e6 d4 d5 Nc3 Nf6' },
  { eco: 'C14', name: 'French, Classical, Steinitz Var.', moves: 'e4 e6 d4 d5 Nc3 Nf6 Bg5 Be7 e5 Nfd7 Bxe7 Qxe7' },
  { eco: 'C18', name: 'French, Winawer Variation',        moves: 'e4 e6 d4 d5 Nc3 Bb4' },
  { eco: 'C19', name: 'French, Winawer, Advance',         moves: 'e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3' },

  // ── Caro-Kann ──────────────────────────────────────────────────────────
  { eco: 'B10', name: 'Caro-Kann Defence',                    moves: 'e4 c6' },
  { eco: 'B10', name: 'Caro-Kann Defence',                    moves: 'e4 c6 d4 d5' },
  { eco: 'B12', name: 'Caro-Kann, Advance Variation',         moves: 'e4 c6 d4 d5 e5' },
  { eco: 'B13', name: 'Caro-Kann, Exchange Variation',        moves: 'e4 c6 d4 d5 exd5 cxd5' },
  { eco: 'B14', name: 'Caro-Kann, Panov-Botvinnik Attack',    moves: 'e4 c6 d4 d5 exd5 cxd5 c4' },
  { eco: 'B15', name: 'Caro-Kann, Forgacs Variation',         moves: 'e4 c6 d4 d5 Nc3 Nf6' },
  { eco: 'B16', name: 'Caro-Kann, Bronstein-Larsen Var.',     moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6 Nxf6+ gxf6' },
  { eco: 'B17', name: 'Caro-Kann, Steinitz Variation',        moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7' },
  { eco: 'B18', name: 'Caro-Kann, Classical Variation',       moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5' },
  { eco: 'B19', name: 'Caro-Kann, Classical, Main Line',      moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4' },

  // ── Sicilian Defence ───────────────────────────────────────────────────
  { eco: 'B20', name: 'Sicilian Defence',                   moves: 'e4 c5' },
  { eco: 'B21', name: 'Sicilian, Smith-Morra Gambit',       moves: 'e4 c5 d4 cxd4 c3' },
  { eco: 'B22', name: 'Sicilian, Alapin Variation',         moves: 'e4 c5 c3' },
  { eco: 'B23', name: 'Sicilian, Closed',                   moves: 'e4 c5 Nc3' },
  { eco: 'B27', name: 'Sicilian Defence',                   moves: 'e4 c5 Nf3' },
  { eco: 'B28', name: 'Sicilian, O\'Kelly Variation',       moves: 'e4 c5 Nf3 a6' },
  { eco: 'B30', name: 'Sicilian, Nimzowitsch Variation',    moves: 'e4 c5 Nf3 Nc6' },
  { eco: 'B32', name: 'Sicilian Defence',                   moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4' },
  { eco: 'B36', name: 'Sicilian, Accelerated Dragon',       moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6' },
  { eco: 'B40', name: 'Sicilian Defence',                   moves: 'e4 c5 Nf3 e6' },
  { eco: 'B41', name: 'Sicilian, Kan Variation',            moves: 'e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6' },
  { eco: 'B44', name: 'Sicilian, Taimanov Variation',       moves: 'e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6' },
  { eco: 'B45', name: 'Sicilian, Taimanov Variation',       moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 e6' },
  { eco: 'B50', name: 'Sicilian Defence',                   moves: 'e4 c5 Nf3 d6' },
  { eco: 'B54', name: 'Sicilian Defence',                   moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4' },
  { eco: 'B57', name: 'Sicilian, Sozin Attack',             moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6 Bc4' },
  { eco: 'B60', name: 'Sicilian, Richter-Rauzer Attack',    moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6 Bg5' },
  { eco: 'B70', name: 'Sicilian, Dragon Variation',         moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6' },
  { eco: 'B72', name: 'Sicilian, Dragon, Classical',        moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 Be2' },
  { eco: 'B76', name: 'Sicilian, Dragon, Yugoslav Attack',  moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 O-O-O' },
  { eco: 'B80', name: 'Sicilian, Scheveningen Variation',   moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6' },
  { eco: 'B81', name: 'Sicilian, Scheveningen, Keres Attack',moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 g4' },
  { eco: 'B86', name: 'Sicilian, Sozin Attack',             moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 Bc4' },
  { eco: 'B90', name: 'Sicilian, Najdorf Variation',        moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6' },
  { eco: 'B91', name: 'Sicilian, Najdorf, Zagreb Variation',moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5' },
  { eco: 'B92', name: 'Sicilian, Najdorf, Opocensky Var.',  moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be2' },
  { eco: 'B94', name: 'Sicilian, Najdorf, 6.Bg5',           moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 Nbd7' },
  { eco: 'B96', name: 'Sicilian, Najdorf, 7.f4',            moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4' },
  { eco: 'B97', name: 'Sicilian, Najdorf, 7...Qb6',         moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4 Qb6' },

  // ── Scandinavian ────────────────────────────────────────────────────────
  { eco: 'B01', name: 'Scandinavian Defence',            moves: 'e4 d5' },
  { eco: 'B01', name: 'Scandinavian, Main Line',         moves: 'e4 d5 exd5 Qxd5 Nc3 Qa5' },
  { eco: 'B01', name: 'Scandinavian, Mieses-Kotrc Var.', moves: 'e4 d5 exd5 Nf6' },

  // ── Alekhine / Pirc / Modern ────────────────────────────────────────────
  { eco: 'B02', name: "Alekhine's Defence",                 moves: 'e4 Nf6' },
  { eco: 'B03', name: "Alekhine's Defence, 3.d4",           moves: 'e4 Nf6 e5 Nd5 d4' },
  { eco: 'B04', name: "Alekhine's, Modern Variation",       moves: 'e4 Nf6 e5 Nd5 d4 d6 Nf3' },
  { eco: 'B06', name: 'Modern Defence',                     moves: 'e4 g6' },
  { eco: 'B07', name: 'Pirc Defence',                       moves: 'e4 d6' },
  { eco: 'B07', name: 'Pirc Defence',                       moves: 'e4 d6 d4 Nf6' },
  { eco: 'B08', name: 'Pirc, Classical System',             moves: 'e4 d6 d4 Nf6 Nc3 g6 Nf3' },
  { eco: 'B09', name: 'Pirc, Austrian Attack',              moves: 'e4 d6 d4 Nf6 Nc3 g6 f4' },

  // ── Open games (1.e4 e5) ────────────────────────────────────────────────
  { eco: 'C20', name: "King's Pawn Game",          moves: 'e4 e5' },
  { eco: 'C20', name: "King's Gambit",             moves: 'e4 e5 f4' },
  { eco: 'C21', name: "King's Gambit Accepted",    moves: 'e4 e5 f4 exf4' },
  { eco: 'C30', name: "King's Gambit Declined",    moves: 'e4 e5 f4 Bc5' },
  { eco: 'C31', name: "KGD, Falkbeer Countergambit", moves: 'e4 e5 f4 d5' },
  { eco: 'C23', name: "Bishop's Opening",          moves: 'e4 e5 Bc4' },
  { eco: 'C24', name: "Bishop's Opening, Berlin",  moves: 'e4 e5 Bc4 Nf6' },
  { eco: 'C26', name: 'Vienna Game',               moves: 'e4 e5 Nc3' },
  { eco: 'C27', name: 'Vienna Game, Frankenstein-Dracula', moves: 'e4 e5 Nc3 Nf6 Bc4 Nxe4' },
  { eco: 'C28', name: 'Vienna Game',               moves: 'e4 e5 Nc3 Nc6' },
  { eco: 'C40', name: "King's Knight Opening",     moves: 'e4 e5 Nf3' },
  { eco: 'C40', name: 'Latvian Gambit',            moves: 'e4 e5 Nf3 f5' },
  { eco: 'C41', name: 'Philidor Defence',          moves: 'e4 e5 Nf3 d6' },
  { eco: 'C42', name: "Petrov's Defence",          moves: 'e4 e5 Nf3 Nf6' },
  { eco: 'C43', name: "Petrov, Modern Attack",     moves: 'e4 e5 Nf3 Nf6 d4' },
  { eco: 'C44', name: "King's Pawn Game",          moves: 'e4 e5 Nf3 Nc6' },
  { eco: 'C44', name: 'Scotch Game',               moves: 'e4 e5 Nf3 Nc6 d4' },
  { eco: 'C45', name: 'Scotch Game',               moves: 'e4 e5 Nf3 Nc6 d4 exd4 Nxd4' },
  { eco: 'C47', name: 'Four Knights Game',         moves: 'e4 e5 Nf3 Nc6 Nc3 Nf6' },
  { eco: 'C46', name: 'Three Knights Game',        moves: 'e4 e5 Nf3 Nc6 Nc3' },
  { eco: 'C48', name: 'Four Knights, Spanish Var.', moves: 'e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5' },
  { eco: 'C49', name: 'Four Knights, Double Spanish', moves: 'e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bb4' },
  { eco: 'C50', name: 'Italian Game',              moves: 'e4 e5 Nf3 Nc6 Bc4' },
  { eco: 'C51', name: 'Evans Gambit',              moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 b4' },
  { eco: 'C53', name: 'Italian Game, Classical',   moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 c3' },
  { eco: 'C54', name: 'Italian, Giuoco Pianissimo',moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3' },
  { eco: 'C55', name: 'Two Knights Defence',       moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6' },
  { eco: 'C56', name: 'Two Knights, Max Lange',    moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 d4 exd4 O-O' },
  { eco: 'C57', name: 'Two Knights, Fried Liver',  moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7' },
  { eco: 'C58', name: 'Two Knights, 4.Ng5 d5',     moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5' },

  // ── Ruy Lopez ──────────────────────────────────────────────────────────
  { eco: 'C60', name: 'Ruy Lopez',                         moves: 'e4 e5 Nf3 Nc6 Bb5' },
  { eco: 'C61', name: "Ruy Lopez, Bird's Defence",         moves: 'e4 e5 Nf3 Nc6 Bb5 Nd4' },
  { eco: 'C62', name: 'Ruy Lopez, Old Steinitz Defence',   moves: 'e4 e5 Nf3 Nc6 Bb5 d6' },
  { eco: 'C63', name: 'Ruy Lopez, Schliemann Defence',     moves: 'e4 e5 Nf3 Nc6 Bb5 f5' },
  { eco: 'C64', name: 'Ruy Lopez, Classical Defence',      moves: 'e4 e5 Nf3 Nc6 Bb5 Bc5' },
  { eco: 'C65', name: 'Ruy Lopez, Berlin Defence',         moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6' },
  { eco: 'C67', name: 'Ruy Lopez, Berlin, Rio Gambit',     moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4' },
  { eco: 'C68', name: 'Ruy Lopez, Exchange Variation',     moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Bxc6' },
  { eco: 'C70', name: 'Ruy Lopez, Morphy Defence',         moves: 'e4 e5 Nf3 Nc6 Bb5 a6' },
  { eco: 'C71', name: 'Ruy Lopez, Modern Steinitz Defence',moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 d6' },
  { eco: 'C77', name: 'Ruy Lopez, Morphy Defence',         moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6' },
  { eco: 'C78', name: 'Ruy Lopez, 5.O-O',                  moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O' },
  { eco: 'C80', name: 'Ruy Lopez, Open Variation',         moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Nxe4' },
  { eco: 'C84', name: 'Ruy Lopez, Closed Variation',       moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7' },
  { eco: 'C88', name: 'Ruy Lopez, Closed, Anti-Marshall',  moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O a4' },
  { eco: 'C89', name: 'Ruy Lopez, Marshall Attack',        moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5' },
  { eco: 'C92', name: 'Ruy Lopez, Closed, Rubinstein Var.',moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3' },
];
export { ECO };
